### PR TITLE
Use `ujson to load the dict instead of `yaml`

### PR DESCRIPTION
**Pull request by mrpau-eduard**
## Summary
Hi @benjaoming .
This fixes issue retrieving the assessment item data for English language packs.

## Issues addressed
- #56

### CODE REVIEW

**Comment by mrpau-eduard** [comment]
Need this fix to build the English language pack with subtitles.

**Comment by mrpau-eduard** [comment]
Hi @benjaoming @aronasorman this fix is need to be merge or else we can't build the `en` language pack.

**Comment by benjaoming** [comment]
Interesting, does this mean that data is now JSON and not YAML or just that ujson can auto-detect the format?

**Comment by mrpau-eduard** [comment]
It is already a `JSON` format then I use `ujson` to read the data. 
Same with the `yaml.load` but special characters are not allowed.

**Pull request merged**
